name: erdemli_bel_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  animations: ^2.0.0
  bottom_sheet: ^3.0.0
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_zoom_drawer: ^3.0.2
  font_awesome_flutter: ^10.1.0
  google_fonts: ^1.1.2
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  line_icons: ^2.0.1
  mask_text_input_formatter: ^2.3.0
  provider: ^6.0.3
  shimmer: ^2.0.0
  sliver_tools: ^0.2.6
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.3
  youtube_player_flutter: ^8.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/logo/erdemli_logo_android.jpg"
  image_path_android: "assets/logo/erdemli_logo_android.jpg"
  adaptive_icon_background: "assets/logo/erdemli_logo_android.jpg"
  adaptive_icon_foreground: "assets/logo/erdemli_logo_android.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
